import type { Cultivo } from '../tipos/dominio';

export const CULTIVOS: readonly Cultivo[] = [
  {
    id: 'tomato',
    name: 'Tomato',
    emoji: '🍅',
    sunNeed: 'full',
    spacingCm: 60,
    seasons: ['spring', 'summer'],
    companions: ['basil', 'carrot', 'marigold', 'nasturtium', 'onion'],
    antagonists: ['potato', 'corn', 'fennel'],
    daysToMaturity: 80,
    waterNeeds: 'medium',
  },
  {
    id: 'basil',
    name: 'Basil',
    emoji: '🌿',
    sunNeed: 'full',
    spacingCm: 25,
    seasons: ['spring', 'summer'],
    companions: ['tomato', 'pepper', 'marigold'],
    antagonists: ['fennel'],
    daysToMaturity: 50,
    waterNeeds: 'medium',
  },
  {
    id: 'carrot',
    name: 'Carrot',
    emoji: '🥕',
    sunNeed: 'partial',
    spacingCm: 10,
    seasons: ['spring', 'fall'],
    companions: ['tomato', 'onion', 'radish', 'lettuce'],
    antagonists: ['fennel', 'dill'],
    daysToMaturity: 70,
    waterNeeds: 'medium',
  },
  {
    id: 'lettuce',
    name: 'Lettuce',
    emoji: '🥬',
    sunNeed: 'partial',
    spacingCm: 25,
    seasons: ['spring', 'fall'],
    companions: ['carrot', 'radish', 'strawberry', 'onion'],
    antagonists: ['fennel'],
    daysToMaturity: 55,
    waterNeeds: 'high',
  },
  {
    id: 'pepper',
    name: 'Pepper',
    emoji: '🫑',
    sunNeed: 'full',
    spacingCm: 45,
    seasons: ['spring', 'summer'],
    companions: ['basil', 'onion', 'carrot'],
    antagonists: ['fennel'],
    daysToMaturity: 75,
    waterNeeds: 'medium',
  },
  {
    id: 'cucumber',
    name: 'Cucumber',
    emoji: '🥒',
    sunNeed: 'full',
    spacingCm: 50,
    seasons: ['spring', 'summer'],
    companions: ['bean', 'corn', 'radish', 'sunflower'],
    antagonists: ['potato', 'rosemary'],
    daysToMaturity: 60,
    waterNeeds: 'high',
  },
  {
    id: 'garlic',
    name: 'Garlic',
    emoji: '🧄',
    sunNeed: 'full',
    spacingCm: 15,
    seasons: ['fall', 'winter'],
    companions: ['tomato', 'lettuce', 'cabbage'],
    antagonists: ['bean', 'pea'],
    daysToMaturity: 180,
    waterNeeds: 'low',
  },
  {
    id: 'onion',
    name: 'Onion',
    emoji: '🧅',
    sunNeed: 'full',
    spacingCm: 15,
    seasons: ['spring', 'fall'],
    companions: ['carrot', 'lettuce', 'beet', 'tomato'],
    antagonists: ['bean', 'pea'],
    daysToMaturity: 100,
    waterNeeds: 'low',
  },
  {
    id: 'spinach',
    name: 'Spinach',
    emoji: '🍃',
    sunNeed: 'shade',
    spacingCm: 20,
    seasons: ['spring', 'fall'],
    companions: ['strawberry', 'pea', 'radish'],
    antagonists: [],
    daysToMaturity: 45,
    waterNeeds: 'medium',
  },
  {
    id: 'zucchini',
    name: 'Zucchini',
    emoji: '🥬',
    sunNeed: 'full',
    spacingCm: 70,
    seasons: ['spring', 'summer'],
    companions: ['bean', 'corn', 'radish', 'nasturtium'],
    antagonists: ['potato'],
    daysToMaturity: 55,
    waterNeeds: 'high',
  },
  {
    id: 'bean',
    name: 'Bush Bean',
    emoji: '🫘',
    sunNeed: 'full',
    spacingCm: 20,
    seasons: ['spring', 'summer'],
    companions: ['corn', 'cucumber', 'marigold', 'radish'],
    antagonists: ['onion', 'garlic'],
    daysToMaturity: 55,
    waterNeeds: 'medium',
  },
  {
    id: 'corn',
    name: 'Corn',
    emoji: '🌽',
    sunNeed: 'full',
    spacingCm: 35,
    seasons: ['spring', 'summer'],
    companions: ['bean', 'cucumber', 'zucchini', 'sunflower'],
    antagonists: ['tomato'],
    daysToMaturity: 90,
    waterNeeds: 'medium',
  },
  {
    id: 'strawberry',
    name: 'Strawberry',
    emoji: '🍓',
    sunNeed: 'partial',
    spacingCm: 30,
    seasons: ['spring', 'fall'],
    companions: ['lettuce', 'spinach', 'nasturtium'],
    antagonists: ['cabbage'],
    daysToMaturity: 90,
    waterNeeds: 'medium',
  },
  {
    id: 'rosemary',
    name: 'Rosemary',
    emoji: '🌹',
    sunNeed: 'full',
    spacingCm: 45,
    seasons: ['spring', 'summer', 'fall'],
    companions: ['cabbage', 'bean', 'carrot'],
    antagonists: [],
    daysToMaturity: 100,
    waterNeeds: 'low',
  },
  {
    id: 'mint',
    name: 'Mint',
    emoji: '🌱',
    sunNeed: 'partial',
    spacingCm: 30,
    seasons: ['spring', 'summer', 'fall'],
    companions: ['tomato', 'cabbage', 'lettuce'],
    antagonists: [],
    daysToMaturity: 60,
    waterNeeds: 'high',
  },
  {
    id: 'cilantro',
    name: 'Cilantro',
    emoji: '🌿',
    sunNeed: 'partial',
    spacingCm: 15,
    seasons: ['spring', 'fall'],
    companions: ['spinach', 'tomato', 'bean'],
    antagonists: ['fennel'],
    daysToMaturity: 45,
    waterNeeds: 'medium',
  },
  {
    id: 'radish',
    name: 'Radish',
    emoji: '🔴',
    sunNeed: 'partial',
    spacingCm: 8,
    seasons: ['spring', 'fall'],
    companions: ['carrot', 'lettuce', 'cucumber', 'bean'],
    antagonists: ['fennel'],
    daysToMaturity: 28,
    waterNeeds: 'medium',
  },
  {
    id: 'chard',
    name: 'Swiss Chard',
    emoji: '🥬',
    sunNeed: 'partial',
    spacingCm: 25,
    seasons: ['spring', 'summer', 'fall'],
    companions: ['bean', 'onion', 'cabbage'],
    antagonists: [],
    daysToMaturity: 55,
    waterNeeds: 'medium',
  },
  {
    id: 'cabbage',
    name: 'Cabbage',
    emoji: '🥬',
    sunNeed: 'partial',
    spacingCm: 45,
    seasons: ['spring', 'fall'],
    companions: ['garlic', 'onion', 'dill', 'rosemary'],
    antagonists: ['strawberry', 'tomato'],
    daysToMaturity: 90,
    waterNeeds: 'medium',
  },
  {
    id: 'potato',
    name: 'Potato',
    emoji: '🥔',
    sunNeed: 'full',
    spacingCm: 40,
    seasons: ['spring', 'summer'],
    companions: ['bean', 'cabbage', 'corn', 'marigold'],
    antagonists: ['tomato', 'cucumber', 'sunflower'],
    daysToMaturity: 100,
    waterNeeds: 'medium',
  },
  {
    id: 'sunflower',
    name: 'Sunflower',
    emoji: '🌻',
    sunNeed: 'full',
    spacingCm: 45,
    seasons: ['spring', 'summer'],
    companions: ['cucumber', 'corn', 'bean'],
    antagonists: ['potato'],
    daysToMaturity: 85,
    waterNeeds: 'low',
  },
  {
    id: 'marigold',
    name: 'Marigold',
    emoji: '🌼',
    sunNeed: 'full',
    spacingCm: 25,
    seasons: ['spring', 'summer', 'fall'],
    companions: ['tomato', 'basil', 'bean', 'potato'],
    antagonists: [],
    daysToMaturity: 60,
    waterNeeds: 'low',
  },
  {
    id: 'nasturtium',
    name: 'Nasturtium',
    emoji: '🌸',
    sunNeed: 'partial',
    spacingCm: 30,
    seasons: ['spring', 'summer', 'fall'],
    companions: ['tomato', 'zucchini', 'strawberry', 'radish'],
    antagonists: [],
    daysToMaturity: 50,
    waterNeeds: 'low',
  },
  {
    id: 'dill',
    name: 'Dill',
    emoji: '🌾',
    sunNeed: 'partial',
    spacingCm: 25,
    seasons: ['spring', 'summer'],
    companions: ['cabbage', 'lettuce', 'onion', 'cucumber'],
    antagonists: ['carrot', 'tomato'],
    daysToMaturity: 50,
    waterNeeds: 'medium',
  },
  {
    id: 'fennel',
    name: 'Fennel',
    emoji: '🌿',
    sunNeed: 'full',
    spacingCm: 35,
    seasons: ['spring', 'fall'],
    companions: [],
    antagonists: [
      'tomato',
      'basil',
      'carrot',
      'pepper',
      'cilantro',
      'radish',
      'bean',
    ],
    daysToMaturity: 80,
    waterNeeds: 'medium',
  },
  {
    id: 'pea',
    name: 'Pea',
    emoji: '🫛',
    sunNeed: 'partial',
    spacingCm: 10,
    seasons: ['spring', 'fall'],
    companions: ['carrot', 'radish', 'spinach', 'lettuce'],
    antagonists: ['onion', 'garlic'],
    daysToMaturity: 65,
    waterNeeds: 'medium',
  },
  {
    id: 'beet',
    name: 'Beet',
    emoji: '🟣',
    sunNeed: 'partial',
    spacingCm: 15,
    seasons: ['spring', 'fall'],
    companions: ['onion', 'garlic', 'lettuce', 'cabbage'],
    antagonists: ['bean'],
    daysToMaturity: 60,
    waterNeeds: 'medium',
  },
] as const;

export function buscarCultivo(id: string): Cultivo | undefined {
  return CULTIVOS.find((cultivo) => cultivo.id === id);
}
